[2023-12-11 16:06:05,620][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-12-11 16:06:05,639][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-12-11 16:06:05,640][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-12-11 16:06:05,642][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-12-11 16:06:05,782][__main__][INFO] - Instantiating datamodule <src.datamodules.time_datamodule.TimeDataModule>
[2023-12-11 16:07:41,076][__main__][INFO] - Instantiating model <src.models.time_module.TSModule>
[2023-12-11 16:07:41,286][__main__][INFO] - Instantiating loggers...
[2023-12-11 16:07:41,287][src.utils.instantiators][WARNING] - No logger configs found! Skipping...
[2023-12-11 16:07:41,289][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-12-11 16:07:42,004][__main__][INFO] - Starting testing!
[2023-12-11 16:43:29,454][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-12-11 16:43:29,501][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-12-11 16:43:29,502][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-12-11 16:43:29,503][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-12-11 16:43:29,614][__main__][INFO] - Instantiating datamodule <src.datamodules.time_datamodule.TimeDataModule>
[2023-12-11 16:44:57,382][__main__][INFO] - Instantiating model <src.models.time_module.TSModule>
[2023-12-11 16:44:57,635][__main__][INFO] - Instantiating loggers...
[2023-12-11 16:44:57,636][src.utils.instantiators][WARNING] - No logger configs found! Skipping...
[2023-12-11 16:44:57,637][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-12-11 16:44:58,412][__main__][INFO] - Starting testing!
[2023-12-11 19:24:20,924][src.utils.utils][INFO] - Output dir: /home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/logs/PenDigits_interpret/runs/2023-12-11_16-43-29
[2023-12-19 04:14:50,919][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-12-19 04:14:50,925][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-12-19 04:14:50,925][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-12-19 04:14:50,926][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-12-19 04:14:50,963][__main__][INFO] - Instantiating datamodule <src.datamodules.time_datamodule.TimeDataModule>
[2023-12-19 04:15:07,614][__main__][INFO] - Instantiating model <src.models.time_module.TSModule>
[2023-12-19 04:15:07,814][__main__][INFO] - Instantiating loggers...
[2023-12-19 04:15:07,814][src.utils.instantiators][WARNING] - No logger configs found! Skipping...
[2023-12-19 04:15:07,815][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-12-19 04:15:08,022][__main__][INFO] - Starting testing!
[2023-12-19 04:15:08,485][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/interpret.py", line 119, in evaluate_interpretability
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 706, in test
    return call._call_and_handle_interrupt(
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 901, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 396, in _restore_modules_and_callbacks
    self.restore_model()
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 278, in restore_model
    trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 351, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/tristanbale/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TSModule:
	size mismatch for net.project_inp.weight: copying a param with shape torch.Size([64, 20]) from checkpoint, the shape in current model is torch.Size([64, 1]).
	size mismatch for net.conv1.weight: copying a param with shape torch.Size([128, 20, 3]) from checkpoint, the shape in current model is torch.Size([128, 1, 3]).
	size mismatch for net.output_layer.0.weight: copying a param with shape torch.Size([64, 3840]) from checkpoint, the shape in current model is torch.Size([64, 32000]).
	size mismatch for net.output_layer.3.weight: copying a param with shape torch.Size([3, 64]) from checkpoint, the shape in current model is torch.Size([2, 64]).
	size mismatch for net.output_layer.3.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).
[2023-12-19 04:15:08,669][src.utils.utils][INFO] - Output dir: /home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/logs/PenDigits_interpret/runs/2023-12-19_04-14-50
[2023-12-19 04:15:51,005][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-12-19 04:15:51,010][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-12-19 04:15:51,011][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-12-19 04:15:51,011][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-12-19 04:15:51,047][__main__][INFO] - Instantiating datamodule <src.datamodules.time_datamodule.TimeDataModule>
[2023-12-19 04:16:07,701][__main__][INFO] - Instantiating model <src.models.time_module.TSModule>
[2023-12-19 04:16:07,893][__main__][INFO] - Instantiating loggers...
[2023-12-19 04:16:07,894][src.utils.instantiators][WARNING] - No logger configs found! Skipping...
[2023-12-19 04:16:07,894][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-12-19 04:16:08,096][__main__][INFO] - Starting testing!
[2023-12-19 04:16:08,551][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/interpret.py", line 119, in evaluate_interpretability
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 706, in test
    return call._call_and_handle_interrupt(
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 901, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 396, in _restore_modules_and_callbacks
    self.restore_model()
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 278, in restore_model
    trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 351, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/tristanbale/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TSModule:
	size mismatch for net.project_inp.weight: copying a param with shape torch.Size([64, 20]) from checkpoint, the shape in current model is torch.Size([64, 1]).
	size mismatch for net.conv1.weight: copying a param with shape torch.Size([128, 20, 3]) from checkpoint, the shape in current model is torch.Size([128, 1, 3]).
	size mismatch for net.output_layer.0.weight: copying a param with shape torch.Size([64, 3840]) from checkpoint, the shape in current model is torch.Size([64, 32000]).
	size mismatch for net.output_layer.3.weight: copying a param with shape torch.Size([3, 64]) from checkpoint, the shape in current model is torch.Size([2, 64]).
	size mismatch for net.output_layer.3.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).
[2023-12-19 04:16:08,555][src.utils.utils][INFO] - Output dir: /home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/logs/PenDigits_interpret/runs/2023-12-19_04-15-50
[2023-12-19 04:26:45,743][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2023-12-19 04:26:45,747][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2023-12-19 04:26:45,748][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2023-12-19 04:26:45,748][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2023-12-19 04:26:45,785][__main__][INFO] - Instantiating datamodule <src.datamodules.time_datamodule.TimeDataModule>
[2023-12-19 04:27:03,517][__main__][INFO] - Instantiating model <src.models.time_module.TSModule>
[2023-12-19 04:27:03,550][__main__][INFO] - Instantiating loggers...
[2023-12-19 04:27:03,551][src.utils.instantiators][WARNING] - No logger configs found! Skipping...
[2023-12-19 04:27:03,552][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-12-19 04:27:03,747][__main__][INFO] - Starting testing!
[2023-12-19 04:27:04,288][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/interpret.py", line 119, in evaluate_interpretability
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 706, in test
    return call._call_and_handle_interrupt(
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 901, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 396, in _restore_modules_and_callbacks
    self.restore_model()
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 278, in restore_model
    trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 351, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/tristanbale/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TSModule:
	size mismatch for net.project_inp.weight: copying a param with shape torch.Size([64, 20]) from checkpoint, the shape in current model is torch.Size([64, 1]).
	size mismatch for net.conv1.weight: copying a param with shape torch.Size([128, 20, 3]) from checkpoint, the shape in current model is torch.Size([128, 1, 3]).
	size mismatch for net.output_layer.0.weight: copying a param with shape torch.Size([64, 3840]) from checkpoint, the shape in current model is torch.Size([64, 32000]).
	size mismatch for net.output_layer.3.weight: copying a param with shape torch.Size([3, 64]) from checkpoint, the shape in current model is torch.Size([2, 64]).
	size mismatch for net.output_layer.3.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).
[2023-12-19 04:27:04,290][src.utils.utils][INFO] - Output dir: /home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/logs/PenDigits_interpret/runs/2023-12-19_04-26-45
[2024-01-01 01:50:56,011][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2024-01-01 01:50:56,026][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2024-01-01 01:50:56,026][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2024-01-01 01:50:56,026][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2024-01-01 01:50:56,079][__main__][INFO] - Instantiating datamodule <src.datamodules.time_datamodule.TimeDataModule>
[2024-01-01 01:51:02,333][__main__][INFO] - Instantiating model <src.models.time_module.TSModule>
[2024-01-01 01:51:02,583][__main__][INFO] - Instantiating loggers...
[2024-01-01 01:51:02,586][src.utils.instantiators][WARNING] - No logger configs found! Skipping...
[2024-01-01 01:51:02,587][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2024-01-01 01:51:02,871][__main__][INFO] - Starting testing!
[2024-01-01 01:51:03,235][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/interpret.py", line 119, in evaluate_interpretability
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 706, in test
    return call._call_and_handle_interrupt(
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 901, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 396, in _restore_modules_and_callbacks
    self.restore_model()
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 278, in restore_model
    trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 351, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/tristanbale/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TSModule:
	size mismatch for net.project_inp.weight: copying a param with shape torch.Size([64, 24]) from checkpoint, the shape in current model is torch.Size([64, 48]).
	size mismatch for net.conv1.weight: copying a param with shape torch.Size([128, 24, 3]) from checkpoint, the shape in current model is torch.Size([128, 48, 3]).
[2024-01-01 01:51:03,247][src.utils.utils][INFO] - Output dir: /home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/logs/PenDigits_interpret/runs/2024-01-01_01-50-55
[2024-01-01 01:52:40,435][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2024-01-01 01:52:40,440][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2024-01-01 01:52:40,440][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2024-01-01 01:52:40,441][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2024-01-01 01:52:40,486][__main__][INFO] - Instantiating datamodule <src.datamodules.time_datamodule.TimeDataModule>
[2024-01-01 01:52:46,721][__main__][INFO] - Instantiating model <src.models.time_module.TSModule>
[2024-01-01 01:52:46,964][__main__][INFO] - Instantiating loggers...
[2024-01-01 01:52:46,966][src.utils.instantiators][WARNING] - No logger configs found! Skipping...
[2024-01-01 01:52:46,968][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2024-01-01 01:52:47,363][__main__][INFO] - Starting testing!
[2024-01-01 01:52:47,636][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/src/interpret.py", line 119, in evaluate_interpretability
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 706, in test
    return call._call_and_handle_interrupt(
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 901, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 396, in _restore_modules_and_callbacks
    self.restore_model()
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 278, in restore_model
    trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/tristanbale/.local/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 351, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/tristanbale/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TSModule:
	size mismatch for net.project_inp.weight: copying a param with shape torch.Size([64, 24]) from checkpoint, the shape in current model is torch.Size([64, 48]).
	size mismatch for net.conv1.weight: copying a param with shape torch.Size([128, 24, 3]) from checkpoint, the shape in current model is torch.Size([128, 48, 3]).
[2024-01-01 01:52:47,655][src.utils.utils][INFO] - Output dir: /home/tristanbale/wsl_coding/TimeSeries-Interpretability-Robustness/logs/PenDigits_interpret/runs/2024-01-01_01-52-40
